dbfilename redis_cache.rdb
dir /home/vkm2/Documents/github/saas-bench/config/pids
pidfile /home/vkm2/Documents/github/saas-bench/config/pids/redis_cache.pid
bind 127.0.0.1
port 13002
maxmemory 793mb
maxmemory-policy allkeys-lru
appendonly no

save ""


aclfile /home/vkm2/Documents/github/saas-bench/config/redis_cache.acl
