dbfilename redis_queue.rdb
dir /home/vkm2/Documents/github/saas-bench/config/pids
pidfile /home/vkm2/Documents/github/saas-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11002

aclfile /home/vkm2/Documents/github/saas-bench/config/redis_queue.acl
